#!/bin/bash
#SBATCH -A DEEPSCIENCE
#SBATCH -N 1
#SBATCH -J keras-ae
#SBATCH -t 72:00:00
#SBATCH -p shared
#SBATCH --gres=gpu:1
 
module purge
module load cuda
 
pyenv local anaconda3-2.5.0 
mkdir -p /scratch/zuck016
python3 download_data.py qm9 -p /scratch/zuck016/mpnn-data/
python main.py --edge-rep chem_graph --datasetPath /scratch/zuck016/mpnn-data/qm9/dsgdb9nsd/ --epochs 50 --model MPNNv2
